#!/bin/sh
#
# Mount all filesystems
#

case "$1" in
  start)
	sleep 5
 	mount -a
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

